language: elixir
elixir:
- 1.6
otp_release:
- 21.0
before_script:
- mix deps.get
env:
- MIX_ENV=test
script:
- mix credo --strict
- mix coveralls.travis
notifications:
  email: false
deploy:
  provider: heroku
  app: squeeze-run
  run: POOL_SIZE=2 mix ecto.migrate
  api_key:
    secure: n+m0fypeyQbwqV60kjBDnTaaWsh1meqkcJF9YV9VQa30NxYlxHE8bVoz2XsVHvsX3ayIEzTE373TvXx9qBq5Xh3dvZnP/MGmVvnUK9ZJtMBdF7hGnOr30S5EqBB/KGNViMzcjiH15bb9Fq6Mqg997fw8JcXVczYNeidaJHf/SPmQBIDo17Ddi1KwJf+jZALYtyVE6a5QajS0CgKWy1AMdFFYVHsw4a7l9wBjUuaORlhh+3SlE6x9OGmcPYEyLmtS25veyMfU7x4zybq6pVDfRM3h4z4gv3xH6wGa6HOfikUet3CgXRHrpvIEILwXccaCBAD/wWoirrxmIhtj4rsKuCyDFH6H4awoQWoRrkDSx2clCg3T8seF583TDpYWpKlKv1JnrPN8My7fr1M0Nu4eTMUkVssXMdnCZbpWH2ffH9lXKic7/G4nSSYZZXG15kgCm/hQVgMmrKYoetdr9A8PvJVoGcAQueVXj2xuhPNcxE+AhmYjOG3O1qFaza5YaAL/tC8Kz9ui6QZ6jeShmCkDJAuF8bbUHyW/7mqKfA5Xi62sabwzScwkP6FSEXr7T6SspSFVJ62LKSWUPGkasnKJ2iY+N7V8jnOnMJzIvuYWFGZ6SsR9dAeIBrp697tVjYOPVUDG5Fbp5dX18NkvbnNZlbu+AWnJV2XA3U+NoC7EBvo=
