language: elixir
elixir:
- 1.6
otp_release:
- 21.0
before_script:
- mix deps.get
env:
- MIX_ENV=test
script:
- mix credo --strict
- mix coveralls.travis
notifications:
  email: false
deploy:
  provider: heroku
  app: squeeze-run
  run: POOL_SIZE=2 mix ecto.migrate
  api_key:
    secure: LfsZOHE0UAFrS12ESbe75yGMX/K0shzJ/iUCQM+q94ebuW/RNrmfA0TjkPiJsrP6ZCVe1tARaoLMLE3YIRQ/RHWKJZuTfMTePhImC/NtaybEl0zHfMlQbH4dEuF2qrPezcHQF+L9QGZLBpjHQeYxXBn9bHPn7KfUcSjuk2NJIwa2P8duOeBQGu5ENifs6PzVuPk68CGyN1KalA4ezjpQ2KdQjH7QmyGh5Y+UytJgv8B8dxqqANG3/UtUNnMSC0NrH6JwobYBK6S2lUgU7LZ5oo8SLMXgsJgSx/rqoFpuc4Y62sXZbtN+iG9eYQmqXWiheTaEzXLN0OtCLhI4ZidsNemtp0chaaSzHtguqG3xEt3Mioz5Tlhx+/X1FtafvDEzUvutstVqQuaVKYVxXEHkQD3WyaunZToG+96Nd7HO2ZKjx+BSKXajWBLqOc9B37LWdr49RZiWTbdCi5HyIrF3WWgfYKclCn71dzBFxlwZ7NsvRujABjNauB28ckjZL6RQOv+QTVKOr9++BjMNY2y8Q7BiSX+ZgYyzIJl+euPQCHogTTCwube2lQCOFhvXz0zuOkSw3PEz8tYeVewzs4yhkA9UqAvhpPSdrs9m8OJqBAiSIJQq9yYKWki06BT4R3O+b9MMnfhj0C7kgJxLx6wxztjMjDv/XSqxq0gZ3UmzTdQ=
